(in-package :boots)

(defmacro with-screen ((symbol terminal &key root) &body body)
  (setf symbol (or symbol '*screen*))
  `(let* ((,symbol (boots%:make-screen ,terminal :root ,root))
          ,@(unless (eql symbol '*screen*)
              `((*screen* ,symbol))))
     ,@body))

(defun read-event (&optional (screen *screen*))
  (boots%:require-type screen boots%:screen)
  (boots/terminals:read-event (boots%::terminal screen)))

(defun read-event-no-hang (&optional (screen *screen*))
  (boots%:require-type screen boots%:screen)
  (boots/terminals:read-event-no-hang (boots%::terminal screen)))

(defun redraw (&key (screen *screen*) (full nil))
  (boots%:require-type screen boots%:screen)
  (boots%:redraw-screen screen full))

(defun width (pad)
  (boots%:pad-w pad))

(defun height (pad)
  (boots%:pad-h pad))

(defmacro with-simple-borders (&body body)
  `(let ((*border-top-left-char* #\+)
         (*border-top-right-char* #\+)
         (*border-bottom-left-char* #\+)
         (*border-bottom-right-char* #\+)
         (*border-vertical-char* #\|)
         (*border-horizontal-char* #\-))
     ,@body))

(defmacro with-light-borders (&body body)
  `(let ((*border-top-left-char*     (char "┌" 0))
         (*border-top-right-char*    (char "┐" 0))
         (*border-bottom-left-char*  (char "└" 0))
         (*border-bottom-right-char* (char "┘" 0))
         (*border-vertical-char*     (char "│" 0))
         (*border-horizontal-char*   (char "─" 0)))
     ,@body))

(defmacro with-heavy-borders (&body body)
  `(let ((*border-top-left-char*     (char "┏" 0))
         (*border-top-right-char*    (char "┓" 0))
         (*border-bottom-left-char*  (char "┗" 0))
         (*border-bottom-right-char* (char "┛" 0))
         (*border-vertical-char*     (char "┃" 0))
         (*border-horizontal-char*   (char "━" 0)))
     ,@body))
